### ISSUE TITLE
Dynamic configuration - docker labels

### ISSUE THREAD

**Issue by tlex** [aarlint/pathauth#3]
Hi,

I'm trying to configure pathauth over docker labels, I get however stuck at the list of dictionaries expected by `traefik.http.middlewares.pathauth.paths`. I can't find a single example where you have a list anywhere except right at the end of the label.

Do you have any idea how this can be configured? If not - then this issue becomes a feature request - maybe instead of a list of dictionaries, every path should get a unique name which can act as a dictionary key?

Thanks

**Comment by aarlint** [comment]
Hey @tlex I havent tried configuring this with docker labels. We are using kubernetes. 
Traefik gives this example of how to set lists of dictionaries:
 
  - "traefik.http.routers.router0.tls.domains[0].main=foobar"
  - "traefik.http.routers.router0.tls.domains[0].sans=foobar, foobar"
  - "traefik.http.routers.router0.tls.domains[1].main=foobar"
  - "traefik.http.routers.router0.tls.domains[1].sans=foobar, foobar"

So maybe something like this:
- "traefik.http.middlewares.pathauth.paths[0].regex=.*"
- "traefik.http.middlewares.pathauth.paths[0].users[0]=aarlint@gmail.com"

**Comment by tlex** [comment]
Thanks for the research. In the meanwhile, I've used the `--whitelist` option from [thomseddon/traefik-forward-auth/](https://github.com/thomseddon/traefik-forward-auth/)
